export FABRIC_CA_VERSION=1.5.3
export FABRIC_VERSION=2.4.3
export FABRIC_CONTAINER_REGISTRY="${DOCKER_REGISTRY_PROXY}${REGISTRY_DOCKER_IO}hyperledger"

export ARTIFACT_METADATA_CCNAME="artifact-metadata"
export ARTIFACT_CONTENT_CCNAME="artifact-content"
export ARTIFACT_RELATIONSHIP_CCNAME="artifact-relationship"
export LIGHTSWITCH_CCNAME="lightswitch"
