apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaordicledger-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-app
  template:
    metadata:
      labels:
        app: graph-app
    spec:
      containers:
        - name: graph-app
          image: ${GRAPH_PROCESSOR_IMAGE}
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: graph-service
spec:
  selector:
    app: graph-app
  ports:
    - port: 12345
      targetPort: 5678

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: graph-app-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - pathType: Prefix
#         path: "/graph"
#         backend:
#           service:
#             name: graph-service
#             port:
#               number: 12345
