- hosts: all
  become: yes
  gather_facts: no
  
  vars:
    proxy_env:
      http_proxy: '{{ lookup("env", "http_proxy") }}'
      https_proxy: '{{ lookup("env", "https_proxy") }}'
      no_proxy: '{{ lookup("env", "no_proxy") }}'

  tasks:
    - name: uninstall certain python modules for docker
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: absent
      with_items:
      - { name: docker-py, version: 1.10.6 }

    - name: install certain python modules for docker
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present
      with_items:
      - { name: docker, version: 2.0.0 }
      # - { name: docker-py, version: 1.10.6 }

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: epel
        description: epel
        mirrorlist: "https://mirrors.fedoraproject.org/mirrorlist?repo=epel-8&arch=x86_64"
        enabled: true
        #gpgcheck: true
        #gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    # - name: Fix epel repo configuration
    #   ansible.builtin.lineinfile:
    #     path: /etc/yum.repos.d/epel.repo
    #     regexp: '^baseurl='
    #     line: mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=epel-8&arch=x86_64

    - name: Execute system update
      dnf:
        name: "*"
        state: latest
        disable_gpg_check: true

    - name: Remove docker if installed from CentOS repo
      dnf:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: Install yum utils
      dnf:
        name:
          - yum-utils
        state: latest

    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "centos"
        #mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install jq
      dnf:
        name:
          - jq
        state: latest

    - name: Install docker
      dnf:
        name:
          - docker-ce
        state: latest

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user cloud-user to docker group
      user:
        name: cloud-user
        groups: docker
        append: yes

    - name: Install curl and wget
      dnf:
        name:
          - curl
          - wget
        state: latest

    - name: Check jq is accessible.
      shell:
        cmd: jq --version
      register: result
      check_mode: false
      changed_when: false
      failed_when: result.rc != 0
